_target_: src.models.model.ResNetClassifier
backbone_name: "resnet50"
hidden_dims: [32]           # No hidden layer if you prefer a single linear classifier on the backbone output
activation: "ReLU"
batch_norm: true
dropout: 0.2
num_classes: 1
freeze_backbone: false