_target_: src.models.model.ViTClassifier
backbone_name: "vit_base_patch16_224"
hidden_dims: [32]         # You can adjust these values
activation: "ReLU"
batch_norm: true
dropout: 0.2
num_classes: 1
freeze_backbone: false