train:
  _target_: src.utils.dataset.RealColonDataset
  data_dir: "/radraid/dongwoolee/real_colon_data/"
  frames_csv: "/radraid2/dongwoolee/Colon/data/frames_train.csv"
  sampling: "undersample"      # Options: "undersample", "oversample", or null
  pos_ratio: 0.5
  transform:
    _target_: src.utils.transform.CustomTransform
    pad_method: "zeros"
    max_size: [1352, 1080]
    target_size: [224, 224]
    augment: true
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
valid:
  _target_: src.utils.dataset.RealColonDataset
  data_dir: "/radraid/dongwoolee/real_colon_data/"
  frames_csv: "/radraid2/dongwoolee/Colon/data/frames_val.csv"
  sampling: "undersample"
  pos_ratio: 0.5
  transform:
    _target_: src.utils.transform.CustomTransform
    pad_method: "zeros"
    max_size: [1352, 1080]
    target_size: [224, 224]
    augment: false
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
test:
  _target_: src.utils.dataset.RealColonDataset
  data_dir: "/radraid/dongwoolee/real_colon_data/"
  frames_csv: "/radraid2/dongwoolee/Colon/data/frames_test.csv"
  sampling: null
  pos_ratio: 0.5
  transform:
    _target_: src.utils.transform.CustomTransform
    pad_method: "zeros"
    max_size: [1352, 1080]
    target_size: [224, 224]
    augment: false
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]