defaults:
  - model: vit
  - loss: bce
  - optimizer: adamw
  - scheduler: cosine
  - dataset: realcolon

# Global settings
seed: 42
epochs: 5
batch_size: 64
learning_rate: 0.0001

wandb:
  entity: "rlee8517-ucla"
  project: "Real Colon"